### ISSUE TITLE
Non valid icon used

### ISSUE THREAD

**Issue by linuxstony** [chunkysteveo/OpenEPaperLink-HA-Weatherman#4] opened 2023-11-11 18:13 UTC
Hi,

I added the configuration part to configuration.yaml and added the automation as instructed. met.no and sun integration were already present, i only added the moon one.

I added my epaper ID in the automation like this.

target:
  entity_id:
    - open_epaper_link.0000021E72E67430

I hope this is correct. 

When i try to fire the automation by hand it throws the above error - as there are multiple icons used in the automation I am at a loss were to start.

My wife and I would be immensely grateful for any help.

Thanks in advance - Stefan

**Comment by chunkysteveo** [comment] 2023-11-12 09:17
Hi!

Can you get the weatherman template data and paste it here? You need to go to Developer Tools.m States, and then in Entity type your weatherman sensor to bring it up.... copy the result here, e.g.

![Screenshot_20231112_091457_Home Assistant](https://github.com/chunkysteveo/OpenEPaperLink-HA-Weatherman/assets/14663002/f117c804-2ccf-4f82-8490-f7b435746493)

That should show us what data is being generated for the tags.

**Comment by chunkysteveo** [comment] 2023-11-15 09:28
May be related to the version of the HA integration - see [issue 6](https://github.com/chunkysteveo/OpenEPaperLink-HA-Weatherman/issues/6)

**Comment by svenove** [comment] 2023-11-15 09:54
Could also be caused by using an old version of the automation, that doesn’t handle the change in Met.no regarding sun/night reference.

**Comment by linuxstony** [comment] 2023-11-15 11:50
Thanks for the suggestions. Will try and check as soon as I leave the hospital. This weather display would be such a goodie for my wife. I HAVE to get this working 😁

Gesendet von Outlook für Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by chunkysteveo** [comment] 2023-11-15 11:57
haha, hope you are all OK!?

Happy wife = happy life!!

**Comment by chunkysteveo** [comment] 2023-11-15 11:58
> Could also be caused by using an old version of the automation, that doesn’t handle the change in Met.no regarding sun/night reference.

Very true - use the latest version of the ha-configuration and automation if you can.

**Comment by chunkysteveo** [comment] 2024-01-02 10:48
Hope you are back to health @linuxstony ? Is this working for you now?

**Comment by linuxstony** [comment] 2024-01-03 07:06
Hi,

I forgot about this after I got a custom display working after my wife
asked for some features displayed on the display that "Weatherman" could
not provide (Mainly sunrise and sunset and the indication if post is in the
letterbox and honey has been sold from the self-service shelf)

I will try again with a 2,9" and report back to you.

Am Di., 2. Jan. 2024 um 11:49 Uhr schrieb Stephen Ludgate <
***@***.***>:

**Comment by chunkysteveo** [comment] 2024-01-03 09:46
No problem!

Re: Sunset, Sunrise - if you check out my "4.2 kitchen sink" automation, you can find I have implemented times for Sun rise and set times - that may help you too??

**Comment by chunkysteveo** [comment] 2024-03-18 13:47
Closing this off, as I see your letterbox and honey custom tags are working well! 🐝

**Closed by chunkysteveo** 2024-03-18 13:47 UTC
